

services:
  db-sodre:
    image: mysql:8.0
    container_name: mysql_sodre
    restart: always
    env_file:
      - ../.env
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: